### regi√£o | estado | data | casosNovos | casosAcumulados | obitosNovos | obitosAcumulados

In [51]:
import pandas as pd
from IPython.display import display
import warnings
import os
import glob

warnings.filterwarnings('ignore')

In [50]:
arquivo_xlsx = glob.glob("*.xlsx")[0]

IndexError: list index out of range

In [2]:
df = pd.read_excel(arquivo_xlsx)
df = df[["regiao", "estado", "data", "casosAcumulado", "obitosAcumulado"]]

In [3]:
df1 = df[df.regiao.eq('Brasil')]
df1['casosNovos'] = df1['casosAcumulado'].diff().abs()
df1['obitosNovos'] = df1['obitosAcumulado'].diff().abs()
df1['casosNovos'][0] = df1.iloc[0].casosAcumulado
df1['obitosNovos'][0] = df1.iloc[0].obitosAcumulado
with pd.option_context('display.max_rows', 1000, 'display.max_columns', 10):
    display(df1.head(1000))
df = df[df.regiao != 'Brasil']

,regiao,estado,data,casosAcumulado,obitosAcumulado,casosNovos,obitosNovos
0,Brasil,NaN,2020-02-26,1,0,1.0,0.0
1,Brasil,NaN,2020-02-27,1,0,0.0,0.0
2,Brasil,NaN,2020-02-28,1,0,0.0,0.0
3,Brasil,NaN,2020-02-29,2,0,1.0,0.0
4,Brasil,NaN,2020-03-01,2,0,0.0,0.0
5,Brasil,NaN,2020-03-02,2,0,0.0,0.0
6,Brasil,NaN,2020-03-03,2,0,0.0,0.0
7,Brasil,NaN,2020-03-04,3,0,1.0,0.0
8,Brasil,NaN,2020-03-05,7,0,4.0,0.0
9,Brasil,NaN,2020-03-06,13,0,6.0,0.0
10,Brasil,NaN,2020-03-07,19,0,6.0,0.0
11,Brasil,NaN,2020-03-08,25,0,6.0,0.0
12,Brasil,NaN,2020-03-09,25,0,0.0,0.0
13,Brasil,NaN,2020-03-10,34,0,9.0,0.0
14,Brasil,NaN,2020-03-11,52,0,18.0,0.0
15,Brasil,NaN,2020-03-12,77,0,25.0,0.0
16,Brasil,NaN,2020-03-13,98,0,21.0,0.0
17,Brasil,NaN,2020-03-14,121,0,23.0,0.0
18,Brasil,NaN,2020-03-15,200,0,79.0,0.0
19,Brasil,NaN,2020-03-16,234,0,34.0,0.0
20,Brasil,NaN,2020-03-17,291,1,57.0,1.0
21,Brasil,NaN,2020-03-18,428,4,137.0,3.0
22,Brasil,NaN,2020-03-19,621,6,193.0,2.0
23,Brasil,NaN,2020-03-20,904,11,283.0,5.0
24,Brasil,NaN,2020-03-21,1128,18,224.0,7.0
25,Brasil,NaN,2020-03-22,1546,25,418.0,7.0
26,Brasil,NaN,2020-03-23,1891,34,345.0,9.0
27,Brasil,NaN,2020-03-24,2201,46,310.0,12.0
28,Brasil,NaN,2020-03-25,2433,57,232.0,11.0
29,Brasil,NaN,2020-03-26,2915,77,482.0,20.0
30,Brasil,NaN,2020-03-27,3417,92,502.0,15.0
31,Brasil,NaN,2020-03-28,3903,114,486.0,22.0
32,Brasil,NaN,2020-03-29,4256,136,353.0,22.0
33,Brasil,NaN,2020-03-30,4579,159,323.0,23.0
34,Brasil,NaN,2020-03-31,5717,201,1138.0,42.0
35,Brasil,NaN,2020-04-01,6834,241,1117.0,40.0
36,Brasil,NaN,2020-04-02,7910,299,1076.0,58.0
37,Brasil,NaN,2020-04-03,9056,359,1146.0,60.0
38,Brasil,NaN,2020-04-04,10278,432,1222.0,73.0
39,Brasil,NaN,2020-04-05,11130,486,852.0,54.0
40,Brasil,NaN,2020-04-06,12056,553,926.0,67.0
41,Brasil,NaN,2020-04-07,13717,667,1661.0,114.0
42,Brasil,NaN,2020-04-08,15927,800,2210.0,133.0
43,Brasil,NaN,2020-04-09,17857,941,1930.0,141.0
44,Brasil,NaN,2020-04-10,19638,1056,1781.0,115.0
45,Brasil,NaN,2020-04-11,20727,1124,1089.0,68.0
46,Brasil,NaN,2020-04-12,22169,1223,1442.0,99.0
47,Brasil,NaN,2020-04-13,23430,1328,1261.0,105.0
48,Brasil,NaN,2020-04-14,25262,1532,1832.0,204.0
49,Brasil,NaN,2020-04-15,28320,1736,3058.0,204.0
50,Brasil,NaN,2020-04-16,30425,1924,2105.0,188.0
51,Brasil,NaN,2020-04-17,33682,2141,3257.0,217.0
52,Brasil,NaN,2020-04-18,36599,2347,2917.0,206.0
53,Brasil,NaN,2020-04-19,38654,2462,2055.0,115.0
54,Brasil,NaN,2020-04-20,40581,2575,1927.0,113.0
55,Brasil,NaN,2020-04-21,43079,2741,2498.0,166.0
56,Brasil,NaN,2020-04-22,45757,2906,2678.0,165.0
57,Brasil,NaN,2020-04-23,49492,3313,3735.0,407.0
58,Brasil,NaN,2020-04-24,52995,3670,3503.0,357.0
59,Brasil,NaN,2020-04-25,58509,4016,5514.0,346.0
60,Brasil,NaN,2020-04-26,61888,4205,3379.0,189.0
61,Brasil,NaN,2020-04-27,66501,4543,4613.0,338.0
62,Brasil,NaN,2020-04-28,71886,5017,5385.0,474.0
63,Brasil,NaN,2020-04-29,78162,5466,6276.0,449.0
64,Brasil,NaN,2020-04-30,85380,5901,7218.0,435.0
65,Brasil,NaN,2020-05-01,91299,6329,5919.0,428.0
66,Brasil,NaN,2020-05-02,96396,6724,5097.0,395.0
67,Brasil,NaN,2020-05-03,101147,7025,4751.0,301.0
68,Brasil,NaN,2020-05-04,107780,7321,6633.0,296.0
69,Brasil,NaN,2020-05-05,114715,7921,6935.0,600.0
70,Brasil,NaN,2020-05-06,125218,8535,10503.0,614.0
71,Brasil,NaN,2020-05-07,135106,9146,9888.0,611.0
72,Brasil,NaN,2020-05-08,145328,9897,10222.0,751.0
73,Brasil,NaN,2020-05-09,155939,10627,10611.0,730.0
74,Brasil,NaN,2020-05-10,162699,11123,6760.0,496.0
75,Brasil,NaN,2020-05-11,168331,11519,5632.0,396.0
76,Brasil,NaN,2020-05-12,177589,12400,9258.0,881.0
77,Brasil,NaN,2020-05-13,188974,13149,11385.0,749.0
78,Brasil,NaN,2020-05-14,202918,13993,13944.0,844.0
79,Brasil,NaN,2020-05-15,218223,14817,15305.0,824.0
80,Brasil,NaN,2020-05-16,233142,15633,14919.0,816.0
81,Brasil,NaN,2020-05-17,241080,16118,7938.0,485.0

In [4]:
estados = df.estado.unique()
len(estados)

27

In [5]:
for i in estados:
    df2 = df[df.estado.eq(i)]
    df2 = df2.sort_values(by='data', ascending=False)
    df2 = df2.groupby(["regiao", "estado", "data"])['casosAcumulado', 'obitosAcumulado'].sum()

    df2['casosNovos'] = df2['casosAcumulado'].diff().abs()
    df2['obitosNovos'] = df2['obitosAcumulado'].diff().abs()
    df2.reset_index(inplace=True)
    df2.loc[:0].casosAcumulado[0]
    df2['casosNovos'][0] = df2.iloc[0].casosAcumulado
    df2['obitosNovos'][0] = df2.iloc[0].obitosAcumulado
    df1 = pd.concat([df1, df2])

In [6]:
df = df1[df1.regiao != 'Brasil']
df = df[['regiao', 'estado', 'data', 'casosNovos', 'casosAcumulado', 'obitosNovos', 'obitosAcumulado']]
df.columns = "regiao", "estado", "data", "casosNovos", "casosAcumulados", "obitosNovos", "obitosAcumulados"
df

,regiao,estado,data,casosNovos,casosAcumulados,obitosNovos,obitosAcumulados
0,Centro-Oeste,MS,2020-03-16,2.0,2,0.0,0
1,Centro-Oeste,MS,2020-03-17,2.0,4,0.0,0
2,Centro-Oeste,MS,2020-03-18,3.0,7,0.0,0
3,Centro-Oeste,MS,2020-03-19,0.0,7,0.0,0
4,Centro-Oeste,MS,2020-03-20,2.0,9,0.0,0
...,...,...,...,...,...,...,...
64,Sul,RS,2020-05-13,0.0,5834,0.0,222
65,Sul,RS,2020-05-14,160.0,5994,18.0,240
66,Sul,RS,2020-05-15,1200.0,7194,12.0,252
67,Sul,RS,2020-05-16,196.0,7390,12.0,264
68,Sul,RS,2020-05-17,80.0,7470,20.0,284

In [7]:
df.to_csv(r'arquivo_geral.csv', index = False, sep=';')

In [ ]:
os.remove(arquivo_xlsx)